name: Publish to TestPyPI

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.1

jobs:
  build-and-publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Upgrade pip and install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build the package
      run: python -m build

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
